import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      {/* Make sure the body has h-full and doesn't forcefully impose flex layouts if children manage it */}
      <body className="h-full bg-zinc-950 text-zinc-50 antialiased">
        {children}
        <Toaster closeButton position="top-right" />
      </body>
    </html>
  );
}
